In [2]:
import torch
from torch import nn
import torch.nn.functional as F
from models.entmax import EntmaxAlpha
from transformers.modeling_bert import BertLayerNorm
from pathlib import Path
home = str(Path.home())

I0212 03:50:47.891784 139678524701568 file_utils.py:35] PyTorch version 1.4.0+cpu available.
/glob/intel-python/python3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
att_dict = torch.load(home+'/snap/interpret.pth', map_location=torch.device('cpu'))

In [4]:
entmax_alpha = EntmaxAlpha(12)

## Check

In [5]:
lang_att_0 = att_dict['lang_att_0']

In [6]:
entmax_alpha.alpha_chooser = lang_att_0['entmax_alpha']

In [7]:
entmax_alpha(lang_att_0['attention_scores'])

tensor([[[[0.0000e+00, 1.8915e-01, 1.9508e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [8.8605e-03, 0.0000e+00, 9.9114e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [6.9196e-01, 1.2663e-02, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [9.8104e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [9.5624e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [8.9811e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 6.8628e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [5.6126e-01, 0.0000e+00, 5.0674e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [6.4429e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [8.8191e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [8]:
lang_att_0['attention_probs']

tensor([[[[0.0000e+00, 1.9113e-01, 4.0953e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 1.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [7.1332e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [9.9928e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [9.8220e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [9.2442e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 5.5765e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [5.7746e-01, 0.0000e+00, 1.5629e-04,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [6.5008e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [8.9781e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [9]:
lang_att_1 = att_dict['lang_att_1']

In [10]:
entmax_alpha.alpha_chooser = lang_att_1['entmax_alpha']

In [11]:
entmax_alpha(lang_att_1['attention_scores'])

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [7.5469e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [2.8217e-01, 1.5754e-01, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [6.8133e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [6.6520e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [6.9635e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 7.8333e-02, 2.5060e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [6.6152e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [7.0868e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [6.9794e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [12]:
lang_att_2 = att_dict['lang_att_2']

In [13]:
entmax_alpha.alpha_chooser = lang_att_2['entmax_alpha']

In [14]:
entmax_alpha(lang_att_2['attention_scores'])

tensor([[[[0.0000e+00, 1.1532e-01, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [6.4768e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [6.2683e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [7.2568e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [7.1956e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [7.0002e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 1.9774e-01, 1.0879e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [9.5204e-02, 2.3708e-02, 8.7254e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [4.1171e-01, 0.0000e+00, 6.0061e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [1.7668e-01, 0.0000e+00, 1.1398e-02,  ..., 0.0000

In [15]:
lang_att_3 = att_dict['lang_att_3']

In [16]:
lang_att_3['attention_probs']

tensor([[[[0.0000e+00, 1.7448e-01, 2.0761e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [5.8045e-01, 5.1262e-05, 2.8225e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [8.3740e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [6.1981e-01, 2.9245e-04, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [5.7305e-01, 2.0804e-02, 1.0090e-05,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [4.0600e-01, 4.3366e-02, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         [[2.7667e-03, 8.4776e-02, 6.0932e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [4.4787e-01, 2.7842e-06, 1.0637e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [4.6573e-01, 3.8379e-03, 3.3659e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [1.7855e-02, 9.6741e-01, 1.4125e-03,  ..., 0.0000

In [17]:
lang_att_4 = att_dict['lang_att_4']

In [18]:
lang_att_4['attention_probs']

tensor([[[[2.0874e-04, 1.8087e-01, 2.0861e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [1.8591e-01, 9.8465e-04, 2.2710e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [1.9029e-02, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [3.8275e-01, 2.7146e-01, 4.2284e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [8.2112e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [2.0594e-01, 4.0037e-01, 2.4442e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 1.1526e-01, 4.0440e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 1.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 4.2962e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [9.2953e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [19]:
lang_att_5 = att_dict['lang_att_5']

In [20]:
lang_att_5['attention_probs']

tensor([[[[1.1951e-01, 2.6042e-02, 1.8751e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [1.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [1.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [7.6438e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [1.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [8.8397e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         [[1.8306e-01, 1.2212e-01, 1.0825e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [1.8059e-01, 7.3856e-03, 2.0953e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [9.1503e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [1.9042e-02, 9.4372e-01, 1.6907e-02,  ..., 0.0000

In [21]:
lang_att_6 = att_dict['lang_att_6']

In [22]:
lang_att_6['attention_probs']

tensor([[[[2.8566e-01, 8.1852e-02, 2.2107e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 1.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 1.0511e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [1.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [1.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [1.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         [[3.8769e-01, 6.5853e-02, 2.3822e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 1.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [1.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 1.6275e-03,  ..., 0.0000

In [23]:
lang_att_7 = att_dict['lang_att_7']

In [24]:
lang_att_7['attention_probs']

tensor([[[[3.6034e-01, 7.1582e-02, 4.5465e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [5.0777e-01, 1.4162e-02, 7.4887e-05,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [7.0495e-01, 2.4186e-03, 2.5284e-07,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [5.1200e-01, 5.8947e-02, 1.0539e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [6.7971e-01, 2.5977e-02, 1.1240e-04,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [5.4969e-01, 4.9264e-02, 4.2735e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         [[1.8259e-02, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [1.6931e-02, 0.0000e+00, 9.8307e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [8.9531e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [5.7325e-01, 2.2012e-02, 2.2368e-02,  ..., 0.0000

In [25]:
lang_att_8 = att_dict['lang_att_8']

In [26]:
lang_att_8['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [3.0852e-02, 0.0000e+00, 1.3738e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 3.6459e-01, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 2.9449e-01, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 7.6304e-01, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         [[2.4193e-02, 1.7545e-01, 2.6136e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [2.5129e-02, 2.2391e-01, 5.4517e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [3.4012e-02, 1.6388e-01, 1.2291e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [3.2854e-03, 6.9668e-02, 1.7911e-02,  ..., 0.0000

In [27]:
visn_att_0 = att_dict['visn_att_0']

In [28]:
visn_att_0['attention_probs']

tensor([[[[1.0946e-02, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           8.2993e-02, 2.5636e-01],
          [0.0000e+00, 0.0000e+00, 4.5689e-02,  ..., 1.1375e-04,
           0.0000e+00, 2.4707e-01],
          [1.9432e-05, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           8.8659e-02, 7.4251e-02],
          ...,
          [1.2204e-02, 0.0000e+00, 9.8664e-03,  ..., 0.0000e+00,
           5.1503e-02, 9.7823e-02],
          [4.0311e-03, 1.9545e-03, 1.4132e-05,  ..., 5.5741e-07,
           1.9995e-02, 4.3035e-02],
          [0.0000e+00, 0.0000e+00, 1.6724e-09,  ..., 2.7815e-03,
           3.6272e-02, 1.3468e-01]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.6200e-02, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.8319e-01, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.6878e-01, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [29]:
visn_att_1 = att_dict['visn_att_1']

In [30]:
visn_att_1['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 1.3927e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [6.9976e-02, 3.3161e-01, 3.2643e-02,  ..., 2.6540e-02,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 7.0268e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           5.5025e-01, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 5.5789e-01]],

         [[2.3647e-02, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 1.8959e-01, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 5.0389e-01,  ..., 1.7534e-03,
           0.0000e+00, 8.7903e-02],
          ...,
          [1.6328e-02, 0.0000e+00, 0.0000e+00,  ..., 9.8066

In [31]:
visn_att_2 = att_dict['visn_att_2']

In [32]:
visn_att_2['attention_probs']

tensor([[[[2.0830e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 1.7126e-01, 0.0000e+00,  ..., 0.0000e+00,
           8.1189e-02, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 1.1954e-01,  ..., 0.0000e+00,
           0.0000e+00, 3.7180e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 2.8444e-01,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 1.3976e-02,  ..., 2.5752e-02,
           0.0000e+00, 4.3381e-01]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 8.2490e-02,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.1432e-02, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 2.2888e-02,  ..., 1.6377e-01,
           0.0000e+00, 4.5314e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 6.9401

In [33]:
visn_att_3 = att_dict['visn_att_3']

In [34]:
visn_att_3['attention_probs']

tensor([[[[5.0161e-03, 7.2154e-03, 1.6494e-02,  ..., 3.1775e-04,
           2.0295e-02, 2.0516e-02],
          [5.7230e-03, 1.5122e-02, 1.2252e-02,  ..., 1.8097e-02,
           2.1061e-02, 3.6021e-02],
          [9.5904e-04, 2.7840e-03, 3.3829e-02,  ..., 8.5520e-03,
           1.1168e-02, 6.1535e-02],
          ...,
          [4.2109e-02, 5.6344e-03, 2.3756e-01,  ..., 2.6177e-02,
           5.1919e-04, 4.1939e-03],
          [3.2178e-04, 4.7339e-03, 1.6029e-03,  ..., 6.1756e-03,
           2.8914e-01, 6.8248e-02],
          [2.3389e-03, 8.8437e-04, 3.2958e-03,  ..., 2.2129e-02,
           3.5367e-02, 1.4054e-01]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [3.6336e-05, 2.8634e-01, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 4.5243e-02,  ..., 7.9746e-02,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [35]:
visn_att_4 = att_dict['visn_att_4']

In [36]:
visn_att_4['attention_probs']

tensor([[[[1.3660e-01, 5.4776e-06, 9.7531e-06,  ..., 2.0127e-09,
           8.4707e-05, 1.9392e-05],
          [2.5798e-02, 1.7505e-02, 1.2661e-05,  ..., 6.0691e-07,
           1.5284e-03, 3.6276e-08],
          [1.1676e-03, 1.4417e-02, 5.7541e-01,  ..., 5.4219e-02,
           7.7715e-04, 2.5285e-02],
          ...,
          [1.3378e-01, 6.3128e-02, 7.9980e-02,  ..., 4.7873e-02,
           3.5286e-03, 4.5480e-03],
          [1.1368e-01, 9.6209e-04, 4.6256e-05,  ..., 5.8870e-04,
           1.7066e-01, 6.0819e-03],
          [0.0000e+00, 2.4270e-05, 3.6919e-02,  ..., 2.2628e-02,
           2.4368e-02, 1.4144e-01]],

         [[1.0435e-02, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 6.1737e-03, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 3.2331e-01,  ..., 4.1570e-02,
           0.0000e+00, 3.1688e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 1.0627e-01,  ..., 4.2974

In [37]:
cross_att_0 = att_dict['cross_att_0']

In [38]:
cross_att_0_cross_lang_att = cross_att_0['cross_lang_att']

In [39]:
cross_att_0_cross_visn_att = cross_att_0['cross_lang_att']

In [40]:
cross_att_0_self_lang_att = cross_att_0['cross_lang_att']

In [41]:
cross_att_0_self_visn_att = cross_att_0['cross_lang_att']

In [42]:
cross_att_0_cross_lang_att['attention_probs']

tensor([[[[0.0000e+00, 2.7229e-01, 0.0000e+00,  ..., 2.3727e-01,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           7.6946e-04, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 3.3101e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 5.0110e-02,  ..., 0.0000e+00,
           2.2062e-01, 1.5130e-03],
          [1.8470e-02, 3.1238e-02, 6.2737e-02,  ..., 4.1355e-02,
           2.7187e-06, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 4.3874e-02,  ..., 0.0000e+00,
           2.2059e-01, 6.2331e-04]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.5795e-01, 1.1352e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           2.7501e-01, 2.1202e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           2.7656e-01, 3.0239e-01],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [43]:
cross_att_0_cross_visn_att['attention_probs']

tensor([[[[0.0000e+00, 2.7229e-01, 0.0000e+00,  ..., 2.3727e-01,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           7.6946e-04, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 3.3101e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 5.0110e-02,  ..., 0.0000e+00,
           2.2062e-01, 1.5130e-03],
          [1.8470e-02, 3.1238e-02, 6.2737e-02,  ..., 4.1355e-02,
           2.7187e-06, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 4.3874e-02,  ..., 0.0000e+00,
           2.2059e-01, 6.2331e-04]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.5795e-01, 1.1352e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           2.7501e-01, 2.1202e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           2.7656e-01, 3.0239e-01],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [44]:
cross_att_0_self_lang_att['attention_probs']

tensor([[[[0.0000e+00, 2.7229e-01, 0.0000e+00,  ..., 2.3727e-01,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           7.6946e-04, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 3.3101e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 5.0110e-02,  ..., 0.0000e+00,
           2.2062e-01, 1.5130e-03],
          [1.8470e-02, 3.1238e-02, 6.2737e-02,  ..., 4.1355e-02,
           2.7187e-06, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 4.3874e-02,  ..., 0.0000e+00,
           2.2059e-01, 6.2331e-04]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.5795e-01, 1.1352e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           2.7501e-01, 2.1202e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           2.7656e-01, 3.0239e-01],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [45]:
cross_att_0_self_visn_att['attention_probs']

tensor([[[[0.0000e+00, 2.7229e-01, 0.0000e+00,  ..., 2.3727e-01,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           7.6946e-04, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 3.3101e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 5.0110e-02,  ..., 0.0000e+00,
           2.2062e-01, 1.5130e-03],
          [1.8470e-02, 3.1238e-02, 6.2737e-02,  ..., 4.1355e-02,
           2.7187e-06, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 4.3874e-02,  ..., 0.0000e+00,
           2.2059e-01, 6.2331e-04]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.5795e-01, 1.1352e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           2.7501e-01, 2.1202e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           2.7656e-01, 3.0239e-01],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [46]:
cross_att_1 = att_dict['cross_att_1']
cross_att_1_cross_lang_att = cross_att_1['cross_lang_att']
cross_att_1_cross_visn_att = cross_att_1['cross_lang_att']
cross_att_1_self_lang_att = cross_att_1['cross_lang_att']
cross_att_1_self_visn_att = cross_att_1['cross_lang_att']

In [47]:
cross_att_1_cross_lang_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [48]:
cross_att_1_cross_visn_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [49]:
cross_att_1_self_lang_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [50]:
cross_att_1_self_visn_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [51]:
cross_att_2 = att_dict['cross_att_2']

In [52]:
cross_att_2 = att_dict['cross_att_2']
cross_att_2_cross_lang_att = cross_att_1['cross_lang_att']
cross_att_2_cross_visn_att = cross_att_1['cross_lang_att']
cross_att_2_self_lang_att = cross_att_1['cross_lang_att']
cross_att_2_self_visn_att = cross_att_1['cross_lang_att']

In [53]:
cross_att_2_cross_lang_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [54]:
cross_att_2_cross_visn_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [55]:
cross_att_2_self_lang_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [56]:
cross_att_2_self_visn_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [57]:
cross_att_3 = att_dict['cross_att_3']

In [58]:
cross_att_3 = att_dict['cross_att_3']
cross_att_3_cross_lang_att = cross_att_1['cross_lang_att']
cross_att_3_cross_visn_att = cross_att_1['cross_lang_att']
cross_att_3_self_lang_att = cross_att_1['cross_lang_att']
cross_att_3_self_visn_att = cross_att_1['cross_lang_att']

In [59]:
cross_att_3_cross_lang_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [60]:
cross_att_3_cross_visn_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [61]:
cross_att_3_self_lang_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [62]:
cross_att_3_self_visn_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [63]:
cross_att_4 = att_dict['cross_att_4']

In [64]:
cross_att_4 = att_dict['cross_att_4']
cross_att_4_cross_lang_att = cross_att_1['cross_lang_att']
cross_att_4_cross_visn_att = cross_att_1['cross_lang_att']
cross_att_4_self_lang_att = cross_att_1['cross_lang_att']
cross_att_4_self_visn_att = cross_att_1['cross_lang_att']

In [65]:
cross_att_4_cross_lang_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [66]:
cross_att_4_cross_visn_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [67]:
cross_att_4_self_lang_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [68]:
cross_att_4_self_visn_att['attention_probs']

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.4171e-01, 8.4031e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 9.7555e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2464e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.1139e-02, 1.0799e-03],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.2163e-01]],

         [[1.2069e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7542e-03, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 3.2420e-02],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.7998e-02],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [69]:
class GeLU(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,x):
        return F.gelu(x)

In [70]:
logit_fc = nn.Sequential(
            nn.Linear(768, 768 * 2),
            GeLU(),
            BertLayerNorm(768 * 2, eps=1e-12),
            nn.Linear(768 * 2, 3129)
        )

In [71]:
cross_att_4_cross_visn_att['attention_probs'].shape

torch.Size([128, 12, 20, 36])

In [72]:
class BertPooler(nn.Module):
    def __init__(self):
        super(BertPooler, self).__init__()
        self.dense = nn.Linear(768, 768)
        self.activation = nn.Tanh()

    def forward(self, hidden_states):
        first_token_tensor = hidden_states[:, 0]
        pooled_output = self.dense(first_token_tensor)
        pooled_output = self.activation(pooled_output)
        return pooled_output

In [73]:
pooler = BertPooler()

In [74]:
l = [
    lang_att_0['attention_probs'],
    lang_att_1['attention_probs'],
    lang_att_2['attention_probs'],
    lang_att_3['attention_probs'],
    lang_att_4['attention_probs'],
    lang_att_5['attention_probs'],
    lang_att_6['attention_probs'],
    lang_att_7['attention_probs'],
    lang_att_8['attention_probs'],
    visn_att_0['attention_probs'],
    visn_att_1['attention_probs'],
    visn_att_2['attention_probs'],
    visn_att_3['attention_probs'],
    visn_att_4['attention_probs'],
    cross_att_0_cross_lang_att['attention_probs'],
    cross_att_0_cross_visn_att['attention_probs'],
    cross_att_0_self_lang_att['attention_probs'],
    cross_att_0_self_visn_att['attention_probs'],
    cross_att_1_cross_lang_att['attention_probs'],
    cross_att_1_cross_visn_att['attention_probs'],
    cross_att_1_self_lang_att['attention_probs'],
    cross_att_1_self_visn_att['attention_probs'],
    cross_att_2_cross_lang_att['attention_probs'],
    cross_att_2_cross_visn_att['attention_probs'],
    cross_att_2_self_lang_att['attention_probs'],
    cross_att_2_self_visn_att['attention_probs'],
    cross_att_3_cross_lang_att['attention_probs'],
    cross_att_3_cross_visn_att['attention_probs'],
    cross_att_3_self_lang_att['attention_probs'],
    cross_att_3_self_visn_att['attention_probs'],
    cross_att_4_cross_lang_att['attention_probs'],
    cross_att_4_cross_visn_att['attention_probs'],
    cross_att_4_self_lang_att['attention_probs'],
    cross_att_4_self_visn_att['attention_probs']]

In [76]:
l[10]

tensor([[[[0.0000e+00, 0.0000e+00, 1.3927e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [6.9976e-02, 3.3161e-01, 3.2643e-02,  ..., 2.6540e-02,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 7.0268e-03,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           5.5025e-01, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 5.5789e-01]],

         [[2.3647e-02, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 1.8959e-01, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 5.0389e-01,  ..., 1.7534e-03,
           0.0000e+00, 8.7903e-02],
          ...,
          [1.6328e-02, 0.0000e+00, 0.0000e+00,  ..., 9.8066

In [77]:
attention_probs = l[33]

In [78]:
value_layer = torch.rand(128, 12, 36, 64)

In [79]:
context_layer = torch.matmul(attention_probs, value_layer)
context_layer = context_layer.permute(0, 2, 1, 3).contiguous()
new_context_layer_shape = context_layer.size()[:-2] + (768,)
context_layer = context_layer.view(*new_context_layer_shape)

In [80]:
pooled_output = pooler(context_layer)

In [81]:
logits = logit_fc(pooled_output)

In [82]:
nn.BCEWithLogitsLoss()(logits, torch.rand(128,3129))

tensor(0.7350, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)

In [ ]:
context_layer.shape
pooled_output.shape